"""Add order_code to Order

Revision ID: 315b666ebdff
Revises: 675f979fb612
Create Date: 2026-05-26 23:26:24.155017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315b666ebdff'
down_revision = '675f979fb612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_order_order_code'), 'order', ['order_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_order_code'), table_name='order')
    op.drop_column('order', 'order_code')
    # ### end Alembic commands ###
