"""Add item_code to MenuItem

Revision ID: 675f979fb612
Revises: add_photo_to_review
Create Date: 2026-05-26 22:38:59.981087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675f979fb612'
down_revision = 'add_photo_to_review'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_area', 'branch',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Pagsanjan'::character varying"))
    op.add_column('menu_item', sa.Column('item_code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_menu_item_item_code'), 'menu_item', ['item_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_item_item_code'), table_name='menu_item')
    op.drop_column('menu_item', 'item_code')
    op.alter_column('delivery_area', 'branch',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Pagsanjan'::character varying"))
    # ### end Alembic commands ###
