"""Add reservation_code to Reservation

Revision ID: add_reservation_code
Revises: 
Create Date: 2024-05-27 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_reservation_code'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('reservation_code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_reservation_reservation_code'), 'reservation', ['reservation_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_reservation_code'), table_name='reservation')
    op.drop_column('reservation', 'reservation_code')
    # ### end Alembic commands ###
