"""add_ingredient_code_to_ingredient

Revision ID: b78ce6dc2bba
Revises: 315b666ebdff
Create Date: 2026-05-27 00:17:10.194696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78ce6dc2bba'
down_revision = '315b666ebdff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('ingredient_code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_ingredient_ingredient_code'), 'ingredient', ['ingredient_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_ingredient_code'), table_name='ingredient')
    op.drop_column('ingredient', 'ingredient_code')
    # ### end Alembic commands ###
