"""add_branch_model

Revision ID: d840fb9b7cf8
Revises: add_order_archive_fields
Create Date: 2026-07-14 14:18:01.224018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd840fb9b7cf8'
down_revision = 'add_order_archive_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archive_run')
    with op.batch_alter_table('archive_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archive_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_archive_audit_log_original_id'))

    op.drop_table('archive_audit_log')
    with op.batch_alter_table('archive_permission_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archive_permission_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_archive_permission_audit_log_original_id'))

    op.drop_table('archive_permission_audit_log')
    with op.batch_alter_table('archive_order_chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archive_order_chat_order_original_id'))
        batch_op.drop_index(batch_op.f('ix_archive_order_chat_original_id'))

    op.drop_table('archive_order_chat')
    with op.batch_alter_table('archive_notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archive_notification_created_at'))
        batch_op.drop_index(batch_op.f('ix_archive_notification_original_id'))

    op.drop_table('archive_notification')
    with op.batch_alter_table('archive_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archive_order_archived_at'))
        batch_op.drop_index(batch_op.f('ix_archive_order_created_at'))
        batch_op.drop_index(batch_op.f('ix_archive_order_order_code'))
        batch_op.drop_index(batch_op.f('ix_archive_order_original_id'))

    op.drop_table('archive_order')
    with op.batch_alter_table('archive_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archive_review_order_original_id'))
        batch_op.drop_index(batch_op.f('ix_archive_review_original_id'))

    op.drop_table('archive_review')
    with op.batch_alter_table('archive_reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archive_reservation_created_at'))
        batch_op.drop_index(batch_op.f('ix_archive_reservation_original_id'))

    op.drop_table('archive_reservation')
    with op.batch_alter_table('archive_inventory_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archive_inventory_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_archive_inventory_log_original_id'))

    op.drop_table('archive_inventory_log')
    with op.batch_alter_table('archive_order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archive_order_item_order_original_id'))
        batch_op.drop_index(batch_op.f('ix_archive_order_item_original_id'))

    op.drop_table('archive_order_item')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    op.create_table('archive_order_item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('order_original_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_at_time', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('cost_at_time', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('archive_order_item_pkey'))
    )
    with op.batch_alter_table('archive_order_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archive_order_item_original_id'), ['original_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_archive_order_item_order_original_id'), ['order_original_id'], unique=False)

    op.create_table('archive_inventory_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('previous_stock', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('new_stock', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('archive_inventory_log_pkey'))
    )
    with op.batch_alter_table('archive_inventory_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archive_inventory_log_original_id'), ['original_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_archive_inventory_log_created_at'), ['created_at'], unique=False)

    op.create_table('archive_reservation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reservation_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('branch', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('guest_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('occasion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('booking_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('table_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cancellation_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('archive_reservation_pkey'))
    )
    with op.batch_alter_table('archive_reservation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archive_reservation_original_id'), ['original_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_archive_reservation_created_at'), ['created_at'], unique=False)

    op.create_table('archive_review',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_original_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_featured_in_gallery', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('archive_review_pkey'))
    )
    with op.batch_alter_table('archive_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archive_review_original_id'), ['original_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_archive_review_order_original_id'), ['order_original_id'], unique=False)

    op.create_table('archive_order',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('order_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('branch', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('dining_option', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('amount_tendered', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('change_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('table_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('table_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('delivery_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('delivery_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('rider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('proof_of_delivery_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('xendit_invoice_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('xendit_invoice_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('prep_start_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('prep_end_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('prep_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('processed_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('archive_order_pkey'))
    )
    with op.batch_alter_table('archive_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archive_order_original_id'), ['original_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_archive_order_order_code'), ['order_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_archive_order_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_archive_order_archived_at'), ['archived_at'], unique=False)

    op.create_table('archive_notification',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('archive_notification_pkey'))
    )
    with op.batch_alter_table('archive_notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archive_notification_original_id'), ['original_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_archive_notification_created_at'), ['created_at'], unique=False)

    op.create_table('archive_order_chat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('order_original_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('archive_order_chat_pkey'))
    )
    with op.batch_alter_table('archive_order_chat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archive_order_chat_original_id'), ['original_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_archive_order_chat_order_original_id'), ['order_original_id'], unique=False)

    op.create_table('archive_permission_audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('permission_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('route', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('archive_permission_audit_log_pkey'))
    )
    with op.batch_alter_table('archive_permission_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archive_permission_audit_log_original_id'), ['original_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_archive_permission_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('archive_audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('archive_audit_log_pkey'))
    )
    with op.batch_alter_table('archive_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archive_audit_log_original_id'), ['original_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_archive_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('archive_run',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('triggered_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('archive_run_pkey'))
    )
    # ### end Alembic commands ###
