"""Add ContactMessage model

Revision ID: ebec3c859fdc
Revises: c6cdc89bc0b8
Create Date: 2026-04-27 16:39:30.656162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebec3c859fdc'
down_revision = 'c6cdc89bc0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_menu_item_category'), 'menu_item', ['category'], unique=False)
    op.create_index(op.f('ix_menu_item_is_available'), 'menu_item', ['is_available'], unique=False)
    op.create_index(op.f('ix_menu_item_is_deleted'), 'menu_item', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_order_created_at'), 'order', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_dining_option'), 'order', ['dining_option'], unique=False)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_index(op.f('ix_reservation_created_at'), 'reservation', ['created_at'], unique=False)
    op.create_index(op.f('ix_reservation_status'), 'reservation', ['status'], unique=False)
    op.drop_column('reservation', 'preorder_data')
    op.drop_column('reservation', 'cancel_reason')
    op.create_index(op.f('ix_review_created_at'), 'review', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_status'), 'review', ['status'], unique=False)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_review_status'), table_name='review')
    op.drop_index(op.f('ix_review_created_at'), table_name='review')
    op.add_column('reservation', sa.Column('cancel_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('reservation', sa.Column('preorder_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_reservation_status'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_created_at'), table_name='reservation')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_dining_option'), table_name='order')
    op.drop_index(op.f('ix_order_created_at'), table_name='order')
    op.drop_index(op.f('ix_menu_item_is_deleted'), table_name='menu_item')
    op.drop_index(op.f('ix_menu_item_is_available'), table_name='menu_item')
    op.drop_index(op.f('ix_menu_item_category'), table_name='menu_item')
    # ### end Alembic commands ###
